classdef BatteryStatus < robotics.ros.Message
    %BatteryStatus MATLAB implementation of mavros_msgs/BatteryStatus
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'mavros_msgs/BatteryStatus' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '8ba4ae7c602c5ae6a7e8f3ffb652dc5f' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        Voltage
        Current
        Remaining
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Current', 'Header', 'Remaining', 'Voltage'} % List of non-constant message properties
        ROSPropertyList = {'current', 'header', 'remaining', 'voltage'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = BatteryStatus(msg)
            %BatteryStatus Construct the message object BatteryStatus
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'BatteryStatus', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function voltage = get.Voltage(obj)
            %get.Voltage Get the value for property Voltage
            voltage = single(obj.JavaMessage.getVoltage);
        end
        
        function set.Voltage(obj, voltage)
            %set.Voltage Set the value for property Voltage
            validateattributes(voltage, {'numeric'}, {'nonempty', 'scalar'}, 'BatteryStatus', 'Voltage');
            
            obj.JavaMessage.setVoltage(voltage);
        end
        
        function current = get.Current(obj)
            %get.Current Get the value for property Current
            current = single(obj.JavaMessage.getCurrent);
        end
        
        function set.Current(obj, current)
            %set.Current Set the value for property Current
            validateattributes(current, {'numeric'}, {'nonempty', 'scalar'}, 'BatteryStatus', 'Current');
            
            obj.JavaMessage.setCurrent(current);
        end
        
        function remaining = get.Remaining(obj)
            %get.Remaining Get the value for property Remaining
            remaining = single(obj.JavaMessage.getRemaining);
        end
        
        function set.Remaining(obj, remaining)
            %set.Remaining Set the value for property Remaining
            validateattributes(remaining, {'numeric'}, {'nonempty', 'scalar'}, 'BatteryStatus', 'Remaining');
            
            obj.JavaMessage.setRemaining(remaining);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Voltage = obj.Voltage;
            cpObj.Current = obj.Current;
            cpObj.Remaining = obj.Remaining;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Voltage = strObj.Voltage;
            obj.Current = strObj.Current;
            obj.Remaining = strObj.Remaining;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Voltage = obj.Voltage;
            strObj.Current = obj.Current;
            strObj.Remaining = obj.Remaining;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.mavros_msgs.BatteryStatus.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.mavros_msgs.BatteryStatus;
            obj.reload(strObj);
        end
    end
end
