classdef CamIMUStamp < robotics.ros.Message
    %CamIMUStamp MATLAB implementation of mavros_msgs/CamIMUStamp
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'mavros_msgs/CamIMUStamp' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'ac22af9031671dd528a56f12d0986660' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        TimeClass = robotics.ros.msg.internal.MessageFactory.getClassForType('time') % Dispatch to MATLAB class for message type time
    end
    
    properties (Dependent)
        FrameStamp
        FrameSeqId
    end
    
    properties (Access = protected)
        Cache = struct('FrameStamp', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'FrameSeqId', 'FrameStamp'} % List of non-constant message properties
        ROSPropertyList = {'frame_seq_id', 'frame_stamp'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = CamIMUStamp(msg)
            %CamIMUStamp Construct the message object CamIMUStamp
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function framestamp = get.FrameStamp(obj)
            %get.FrameStamp Get the value for property FrameStamp
            if isempty(obj.Cache.FrameStamp)
                obj.Cache.FrameStamp = feval(obj.TimeClass, obj.JavaMessage.getFrameStamp);
            end
            framestamp = obj.Cache.FrameStamp;
        end
        
        function set.FrameStamp(obj, framestamp)
            %set.FrameStamp Set the value for property FrameStamp
            validateattributes(framestamp, {obj.TimeClass}, {'nonempty', 'scalar'}, 'CamIMUStamp', 'FrameStamp');
            
            obj.JavaMessage.setFrameStamp(framestamp.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.FrameStamp)
                obj.Cache.FrameStamp.setJavaObject(framestamp.getJavaObject);
            end
        end
        
        function frameseqid = get.FrameSeqId(obj)
            %get.FrameSeqId Get the value for property FrameSeqId
            frameseqid = int32(obj.JavaMessage.getFrameSeqId);
        end
        
        function set.FrameSeqId(obj, frameseqid)
            %set.FrameSeqId Set the value for property FrameSeqId
            validateattributes(frameseqid, {'numeric'}, {'nonempty', 'scalar'}, 'CamIMUStamp', 'FrameSeqId');
            
            obj.JavaMessage.setFrameSeqId(frameseqid);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.FrameStamp = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.FrameSeqId = obj.FrameSeqId;
            
            % Recursively copy compound properties
            cpObj.FrameStamp = copy(obj.FrameStamp);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.FrameSeqId = strObj.FrameSeqId;
            obj.FrameStamp = feval([obj.TimeClass '.loadobj'], strObj.FrameStamp);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.FrameSeqId = obj.FrameSeqId;
            strObj.FrameStamp = saveobj(obj.FrameStamp);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.mavros_msgs.CamIMUStamp.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.mavros_msgs.CamIMUStamp;
            obj.reload(strObj);
        end
    end
end
