classdef CommandTriggerControlRequest < robotics.ros.Message
    %CommandTriggerControlRequest MATLAB implementation of mavros_msgs/CommandTriggerControlRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'mavros_msgs/CommandTriggerControlRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'e9392eb8721dabc9986be213994357de' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        TriggerEnable
        CycleTime
    end
    
    properties (Constant, Hidden)
        PropertyList = {'CycleTime', 'TriggerEnable'} % List of non-constant message properties
        ROSPropertyList = {'cycle_time', 'trigger_enable'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = CommandTriggerControlRequest(msg)
            %CommandTriggerControlRequest Construct the message object CommandTriggerControlRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function triggerenable = get.TriggerEnable(obj)
            %get.TriggerEnable Get the value for property TriggerEnable
            triggerenable = logical(obj.JavaMessage.getTriggerEnable);
        end
        
        function set.TriggerEnable(obj, triggerenable)
            %set.TriggerEnable Set the value for property TriggerEnable
            validateattributes(triggerenable, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'CommandTriggerControlRequest', 'TriggerEnable');
            
            obj.JavaMessage.setTriggerEnable(triggerenable);
        end
        
        function cycletime = get.CycleTime(obj)
            %get.CycleTime Get the value for property CycleTime
            cycletime = single(obj.JavaMessage.getCycleTime);
        end
        
        function set.CycleTime(obj, cycletime)
            %set.CycleTime Set the value for property CycleTime
            validateattributes(cycletime, {'numeric'}, {'nonempty', 'scalar'}, 'CommandTriggerControlRequest', 'CycleTime');
            
            obj.JavaMessage.setCycleTime(cycletime);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.TriggerEnable = obj.TriggerEnable;
            cpObj.CycleTime = obj.CycleTime;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.TriggerEnable = strObj.TriggerEnable;
            obj.CycleTime = strObj.CycleTime;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.TriggerEnable = obj.TriggerEnable;
            strObj.CycleTime = obj.CycleTime;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.mavros_msgs.CommandTriggerControlRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.mavros_msgs.CommandTriggerControlRequest;
            obj.reload(strObj);
        end
    end
end
