classdef ExtendedState < robotics.ros.Message
    %ExtendedState MATLAB implementation of mavros_msgs/ExtendedState
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'mavros_msgs/ExtendedState' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'ae780b1800fe17b917369d21b90058bd' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant)
        VTOLSTATEUNDEFINED = uint8(0)
        VTOLSTATETRANSITIONTOFW = uint8(1)
        VTOLSTATETRANSITIONTOMC = uint8(2)
        VTOLSTATEMC = uint8(3)
        VTOLSTATEFW = uint8(4)
        LANDEDSTATEUNDEFINED = uint8(0)
        LANDEDSTATEONGROUND = uint8(1)
        LANDEDSTATEINAIR = uint8(2)
        LANDEDSTATETAKEOFF = uint8(3)
        LANDEDSTATELANDING = uint8(4)
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        VtolState
        LandedState
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Header', 'LandedState', 'VtolState'} % List of non-constant message properties
        ROSPropertyList = {'header', 'landed_state', 'vtol_state'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ExtendedState(msg)
            %ExtendedState Construct the message object ExtendedState
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'ExtendedState', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function vtolstate = get.VtolState(obj)
            %get.VtolState Get the value for property VtolState
            vtolstate = typecast(int8(obj.JavaMessage.getVtolState), 'uint8');
        end
        
        function set.VtolState(obj, vtolstate)
            %set.VtolState Set the value for property VtolState
            validateattributes(vtolstate, {'numeric'}, {'nonempty', 'scalar'}, 'ExtendedState', 'VtolState');
            
            obj.JavaMessage.setVtolState(vtolstate);
        end
        
        function landedstate = get.LandedState(obj)
            %get.LandedState Get the value for property LandedState
            landedstate = typecast(int8(obj.JavaMessage.getLandedState), 'uint8');
        end
        
        function set.LandedState(obj, landedstate)
            %set.LandedState Set the value for property LandedState
            validateattributes(landedstate, {'numeric'}, {'nonempty', 'scalar'}, 'ExtendedState', 'LandedState');
            
            obj.JavaMessage.setLandedState(landedstate);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.VtolState = obj.VtolState;
            cpObj.LandedState = obj.LandedState;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.VtolState = strObj.VtolState;
            obj.LandedState = strObj.LandedState;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.VtolState = obj.VtolState;
            strObj.LandedState = obj.LandedState;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.mavros_msgs.ExtendedState.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.mavros_msgs.ExtendedState;
            obj.reload(strObj);
        end
    end
end
