classdef ParamValue < robotics.ros.Message
    %ParamValue MATLAB implementation of mavros_msgs/ParamValue
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'mavros_msgs/ParamValue' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'e2cb1c7a0f6ef0c62d450cd9362c980d' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Integer
        Real
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Integer', 'Real'} % List of non-constant message properties
        ROSPropertyList = {'integer', 'real'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ParamValue(msg)
            %ParamValue Construct the message object ParamValue
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function integer = get.Integer(obj)
            %get.Integer Get the value for property Integer
            integer = int64(obj.JavaMessage.getInteger);
        end
        
        function set.Integer(obj, integer)
            %set.Integer Set the value for property Integer
            validateattributes(integer, {'numeric'}, {'nonempty', 'scalar'}, 'ParamValue', 'Integer');
            
            obj.JavaMessage.setInteger(integer);
        end
        
        function real = get.Real(obj)
            %get.Real Get the value for property Real
            real = double(obj.JavaMessage.getReal);
        end
        
        function set.Real(obj, real)
            %set.Real Set the value for property Real
            validateattributes(real, {'numeric'}, {'nonempty', 'scalar'}, 'ParamValue', 'Real');
            
            obj.JavaMessage.setReal(real);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Integer = obj.Integer;
            cpObj.Real = obj.Real;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Integer = strObj.Integer;
            obj.Real = strObj.Real;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Integer = obj.Integer;
            strObj.Real = obj.Real;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.mavros_msgs.ParamValue.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.mavros_msgs.ParamValue;
            obj.reload(strObj);
        end
    end
end
