classdef SetModeRequest < robotics.ros.Message
    %SetModeRequest MATLAB implementation of mavros_msgs/SetModeRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'mavros_msgs/SetModeRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'd770431847cad3a8f50a81ec70ddf0e2' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant)
        MAVMODEPREFLIGHT = uint8(0)
        MAVMODESTABILIZEDISARMED = uint8(80)
        MAVMODESTABILIZEARMED = uint8(208)
        MAVMODEMANUALDISARMED = uint8(64)
        MAVMODEMANUALARMED = uint8(192)
        MAVMODEGUIDEDDISARMED = uint8(88)
        MAVMODEGUIDEDARMED = uint8(216)
        MAVMODEAUTODISARMED = uint8(92)
        MAVMODEAUTOARMED = uint8(220)
        MAVMODETESTDISARMED = uint8(66)
        MAVMODETESTARMED = uint8(194)
    end
    
    properties (Dependent)
        BaseMode
        CustomMode
    end
    
    properties (Constant, Hidden)
        PropertyList = {'BaseMode', 'CustomMode'} % List of non-constant message properties
        ROSPropertyList = {'base_mode', 'custom_mode'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = SetModeRequest(msg)
            %SetModeRequest Construct the message object SetModeRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function basemode = get.BaseMode(obj)
            %get.BaseMode Get the value for property BaseMode
            basemode = typecast(int8(obj.JavaMessage.getBaseMode), 'uint8');
        end
        
        function set.BaseMode(obj, basemode)
            %set.BaseMode Set the value for property BaseMode
            validateattributes(basemode, {'numeric'}, {'nonempty', 'scalar'}, 'SetModeRequest', 'BaseMode');
            
            obj.JavaMessage.setBaseMode(basemode);
        end
        
        function custommode = get.CustomMode(obj)
            %get.CustomMode Get the value for property CustomMode
            custommode = char(obj.JavaMessage.getCustomMode);
        end
        
        function set.CustomMode(obj, custommode)
            %set.CustomMode Set the value for property CustomMode
            validateattributes(custommode, {'char'}, {}, 'SetModeRequest', 'CustomMode');
            
            obj.JavaMessage.setCustomMode(custommode);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.BaseMode = obj.BaseMode;
            cpObj.CustomMode = obj.CustomMode;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.BaseMode = strObj.BaseMode;
            obj.CustomMode = strObj.CustomMode;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.BaseMode = obj.BaseMode;
            strObj.CustomMode = obj.CustomMode;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.mavros_msgs.SetModeRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.mavros_msgs.SetModeRequest;
            obj.reload(strObj);
        end
    end
end
