classdef State < robotics.ros.Message
    %State MATLAB implementation of mavros_msgs/State
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'mavros_msgs/State' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '63d9a29b6abd9e0beeba06109556d062' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        Connected
        Armed
        Guided
        Mode
        SystemStatus
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Armed', 'Connected', 'Guided', 'Header', 'Mode', 'SystemStatus'} % List of non-constant message properties
        ROSPropertyList = {'armed', 'connected', 'guided', 'header', 'mode', 'system_status'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = State(msg)
            %State Construct the message object State
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'State', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function connected = get.Connected(obj)
            %get.Connected Get the value for property Connected
            connected = logical(obj.JavaMessage.getConnected);
        end
        
        function set.Connected(obj, connected)
            %set.Connected Set the value for property Connected
            validateattributes(connected, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'State', 'Connected');
            
            obj.JavaMessage.setConnected(connected);
        end
        
        function armed = get.Armed(obj)
            %get.Armed Get the value for property Armed
            armed = logical(obj.JavaMessage.getArmed);
        end
        
        function set.Armed(obj, armed)
            %set.Armed Set the value for property Armed
            validateattributes(armed, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'State', 'Armed');
            
            obj.JavaMessage.setArmed(armed);
        end
        
        function guided = get.Guided(obj)
            %get.Guided Get the value for property Guided
            guided = logical(obj.JavaMessage.getGuided);
        end
        
        function set.Guided(obj, guided)
            %set.Guided Set the value for property Guided
            validateattributes(guided, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'State', 'Guided');
            
            obj.JavaMessage.setGuided(guided);
        end
        
        function mode = get.Mode(obj)
            %get.Mode Get the value for property Mode
            mode = char(obj.JavaMessage.getMode);
        end
        
        function set.Mode(obj, mode)
            %set.Mode Set the value for property Mode
            validateattributes(mode, {'char'}, {}, 'State', 'Mode');
            
            obj.JavaMessage.setMode(mode);
        end
        
        function systemstatus = get.SystemStatus(obj)
            %get.SystemStatus Get the value for property SystemStatus
            systemstatus = typecast(int8(obj.JavaMessage.getSystemStatus), 'uint8');
        end
        
        function set.SystemStatus(obj, systemstatus)
            %set.SystemStatus Set the value for property SystemStatus
            validateattributes(systemstatus, {'numeric'}, {'nonempty', 'scalar'}, 'State', 'SystemStatus');
            
            obj.JavaMessage.setSystemStatus(systemstatus);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Connected = obj.Connected;
            cpObj.Armed = obj.Armed;
            cpObj.Guided = obj.Guided;
            cpObj.Mode = obj.Mode;
            cpObj.SystemStatus = obj.SystemStatus;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Connected = strObj.Connected;
            obj.Armed = strObj.Armed;
            obj.Guided = strObj.Guided;
            obj.Mode = strObj.Mode;
            obj.SystemStatus = strObj.SystemStatus;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Connected = obj.Connected;
            strObj.Armed = obj.Armed;
            strObj.Guided = obj.Guided;
            strObj.Mode = obj.Mode;
            strObj.SystemStatus = obj.SystemStatus;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.mavros_msgs.State.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.mavros_msgs.State;
            obj.reload(strObj);
        end
    end
end
