classdef StreamRateRequest < robotics.ros.Message
    %StreamRateRequest MATLAB implementation of mavros_msgs/StreamRateRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'mavros_msgs/StreamRateRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'd12f7661724c8ba25f67ba597bb7d039' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant)
        STREAMALL = uint8(0)
        STREAMRAWSENSORS = uint8(1)
        STREAMEXTENDEDSTATUS = uint8(2)
        STREAMRCCHANNELS = uint8(3)
        STREAMRAWCONTROLLER = uint8(4)
        STREAMPOSITION = uint8(6)
        STREAMEXTRA1 = uint8(10)
        STREAMEXTRA2 = uint8(11)
        STREAMEXTRA3 = uint8(12)
    end
    
    properties (Dependent)
        StreamId
        MessageRate
        OnOff
    end
    
    properties (Constant, Hidden)
        PropertyList = {'MessageRate', 'OnOff', 'StreamId'} % List of non-constant message properties
        ROSPropertyList = {'message_rate', 'on_off', 'stream_id'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = StreamRateRequest(msg)
            %StreamRateRequest Construct the message object StreamRateRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function streamid = get.StreamId(obj)
            %get.StreamId Get the value for property StreamId
            streamid = typecast(int8(obj.JavaMessage.getStreamId), 'uint8');
        end
        
        function set.StreamId(obj, streamid)
            %set.StreamId Set the value for property StreamId
            validateattributes(streamid, {'numeric'}, {'nonempty', 'scalar'}, 'StreamRateRequest', 'StreamId');
            
            obj.JavaMessage.setStreamId(streamid);
        end
        
        function messagerate = get.MessageRate(obj)
            %get.MessageRate Get the value for property MessageRate
            messagerate = typecast(int16(obj.JavaMessage.getMessageRate), 'uint16');
        end
        
        function set.MessageRate(obj, messagerate)
            %set.MessageRate Set the value for property MessageRate
            validateattributes(messagerate, {'numeric'}, {'nonempty', 'scalar'}, 'StreamRateRequest', 'MessageRate');
            
            obj.JavaMessage.setMessageRate(messagerate);
        end
        
        function onoff = get.OnOff(obj)
            %get.OnOff Get the value for property OnOff
            onoff = logical(obj.JavaMessage.getOnOff);
        end
        
        function set.OnOff(obj, onoff)
            %set.OnOff Set the value for property OnOff
            validateattributes(onoff, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'StreamRateRequest', 'OnOff');
            
            obj.JavaMessage.setOnOff(onoff);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.StreamId = obj.StreamId;
            cpObj.MessageRate = obj.MessageRate;
            cpObj.OnOff = obj.OnOff;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.StreamId = strObj.StreamId;
            obj.MessageRate = strObj.MessageRate;
            obj.OnOff = strObj.OnOff;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.StreamId = obj.StreamId;
            strObj.MessageRate = obj.MessageRate;
            strObj.OnOff = obj.OnOff;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.mavros_msgs.StreamRateRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.mavros_msgs.StreamRateRequest;
            obj.reload(strObj);
        end
    end
end
