classdef TimesyncStatus < robotics.ros.Message
    %TimesyncStatus MATLAB implementation of mavros_msgs/TimesyncStatus
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'mavros_msgs/TimesyncStatus' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '021ec8044e747bea518b441f374ba64b' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        RemoteTimestampNs
        ObservedOffsetNs
        EstimatedOffsetNs
        RoundTripTimeMs
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'EstimatedOffsetNs', 'Header', 'ObservedOffsetNs', 'RemoteTimestampNs', 'RoundTripTimeMs'} % List of non-constant message properties
        ROSPropertyList = {'estimated_offset_ns', 'header', 'observed_offset_ns', 'remote_timestamp_ns', 'round_trip_time_ms'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = TimesyncStatus(msg)
            %TimesyncStatus Construct the message object TimesyncStatus
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'TimesyncStatus', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function remotetimestampns = get.RemoteTimestampNs(obj)
            %get.RemoteTimestampNs Get the value for property RemoteTimestampNs
            remotetimestampns = typecast(int64(obj.JavaMessage.getRemoteTimestampNs), 'uint64');
        end
        
        function set.RemoteTimestampNs(obj, remotetimestampns)
            %set.RemoteTimestampNs Set the value for property RemoteTimestampNs
            validateattributes(remotetimestampns, {'numeric'}, {'nonempty', 'scalar'}, 'TimesyncStatus', 'RemoteTimestampNs');
            
            obj.JavaMessage.setRemoteTimestampNs(remotetimestampns);
        end
        
        function observedoffsetns = get.ObservedOffsetNs(obj)
            %get.ObservedOffsetNs Get the value for property ObservedOffsetNs
            observedoffsetns = int64(obj.JavaMessage.getObservedOffsetNs);
        end
        
        function set.ObservedOffsetNs(obj, observedoffsetns)
            %set.ObservedOffsetNs Set the value for property ObservedOffsetNs
            validateattributes(observedoffsetns, {'numeric'}, {'nonempty', 'scalar'}, 'TimesyncStatus', 'ObservedOffsetNs');
            
            obj.JavaMessage.setObservedOffsetNs(observedoffsetns);
        end
        
        function estimatedoffsetns = get.EstimatedOffsetNs(obj)
            %get.EstimatedOffsetNs Get the value for property EstimatedOffsetNs
            estimatedoffsetns = int64(obj.JavaMessage.getEstimatedOffsetNs);
        end
        
        function set.EstimatedOffsetNs(obj, estimatedoffsetns)
            %set.EstimatedOffsetNs Set the value for property EstimatedOffsetNs
            validateattributes(estimatedoffsetns, {'numeric'}, {'nonempty', 'scalar'}, 'TimesyncStatus', 'EstimatedOffsetNs');
            
            obj.JavaMessage.setEstimatedOffsetNs(estimatedoffsetns);
        end
        
        function roundtriptimems = get.RoundTripTimeMs(obj)
            %get.RoundTripTimeMs Get the value for property RoundTripTimeMs
            roundtriptimems = single(obj.JavaMessage.getRoundTripTimeMs);
        end
        
        function set.RoundTripTimeMs(obj, roundtriptimems)
            %set.RoundTripTimeMs Set the value for property RoundTripTimeMs
            validateattributes(roundtriptimems, {'numeric'}, {'nonempty', 'scalar'}, 'TimesyncStatus', 'RoundTripTimeMs');
            
            obj.JavaMessage.setRoundTripTimeMs(roundtriptimems);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.RemoteTimestampNs = obj.RemoteTimestampNs;
            cpObj.ObservedOffsetNs = obj.ObservedOffsetNs;
            cpObj.EstimatedOffsetNs = obj.EstimatedOffsetNs;
            cpObj.RoundTripTimeMs = obj.RoundTripTimeMs;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.RemoteTimestampNs = strObj.RemoteTimestampNs;
            obj.ObservedOffsetNs = strObj.ObservedOffsetNs;
            obj.EstimatedOffsetNs = strObj.EstimatedOffsetNs;
            obj.RoundTripTimeMs = strObj.RoundTripTimeMs;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.RemoteTimestampNs = obj.RemoteTimestampNs;
            strObj.ObservedOffsetNs = obj.ObservedOffsetNs;
            strObj.EstimatedOffsetNs = obj.EstimatedOffsetNs;
            strObj.RoundTripTimeMs = obj.RoundTripTimeMs;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.mavros_msgs.TimesyncStatus.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.mavros_msgs.TimesyncStatus;
            obj.reload(strObj);
        end
    end
end
