classdef CircleArray < robotics.ros.Message
    %CircleArray MATLAB implementation of opencv_apps/CircleArray
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'opencv_apps/CircleArray' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '1970b146e338dd024c765e522039a727' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        OpencvAppsCircleClass = robotics.ros.msg.internal.MessageFactory.getClassForType('opencv_apps/Circle') % Dispatch to MATLAB class for message type opencv_apps/Circle
    end
    
    properties (Dependent)
        Circles
    end
    
    properties (Access = protected)
        Cache = struct('Circles', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Circles'} % List of non-constant message properties
        ROSPropertyList = {'circles'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = CircleArray(msg)
            %CircleArray Construct the message object CircleArray
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function circles = get.Circles(obj)
            %get.Circles Get the value for property Circles
            if isempty(obj.Cache.Circles)
                javaArray = obj.JavaMessage.getCircles;
                array = obj.readJavaArray(javaArray, obj.OpencvAppsCircleClass);
                obj.Cache.Circles = feval(obj.OpencvAppsCircleClass, array);
            end
            circles = obj.Cache.Circles;
        end
        
        function set.Circles(obj, circles)
            %set.Circles Set the value for property Circles
            if ~isvector(circles) && isempty(circles)
                % Allow empty [] input
                circles = feval([obj.OpencvAppsCircleClass '.empty'], 0, 1);
            end
            
            validateattributes(circles, {obj.OpencvAppsCircleClass}, {'vector'}, 'CircleArray', 'Circles');
            
            javaArray = obj.JavaMessage.getCircles;
            array = obj.writeJavaArray(circles, javaArray, obj.OpencvAppsCircleClass);
            obj.JavaMessage.setCircles(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Circles)
                obj.Cache.Circles = [];
                obj.Cache.Circles = obj.Circles;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Circles = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Circles = copy(obj.Circles);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            CirclesCell = arrayfun(@(x) feval([obj.OpencvAppsCircleClass '.loadobj'], x), strObj.Circles, 'UniformOutput', false);
            obj.Circles = vertcat(CirclesCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Circles = arrayfun(@(x) saveobj(x), obj.Circles);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.opencv_apps.CircleArray.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.opencv_apps.CircleArray;
            obj.reload(strObj);
        end
    end
end
