classdef Circle < robotics.ros.Message
    %Circle MATLAB implementation of opencv_apps/Circle
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'opencv_apps/Circle' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '4f6847051b4fe493b5af8caad66201d5' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        OpencvAppsPoint2DClass = robotics.ros.msg.internal.MessageFactory.getClassForType('opencv_apps/Point2D') % Dispatch to MATLAB class for message type opencv_apps/Point2D
    end
    
    properties (Dependent)
        Center
        Radius
    end
    
    properties (Access = protected)
        Cache = struct('Center', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Center', 'Radius'} % List of non-constant message properties
        ROSPropertyList = {'center', 'radius'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Circle(msg)
            %Circle Construct the message object Circle
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function center = get.Center(obj)
            %get.Center Get the value for property Center
            if isempty(obj.Cache.Center)
                obj.Cache.Center = feval(obj.OpencvAppsPoint2DClass, obj.JavaMessage.getCenter);
            end
            center = obj.Cache.Center;
        end
        
        function set.Center(obj, center)
            %set.Center Set the value for property Center
            validateattributes(center, {obj.OpencvAppsPoint2DClass}, {'nonempty', 'scalar'}, 'Circle', 'Center');
            
            obj.JavaMessage.setCenter(center.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Center)
                obj.Cache.Center.setJavaObject(center.getJavaObject);
            end
        end
        
        function radius = get.Radius(obj)
            %get.Radius Get the value for property Radius
            radius = double(obj.JavaMessage.getRadius);
        end
        
        function set.Radius(obj, radius)
            %set.Radius Set the value for property Radius
            validateattributes(radius, {'numeric'}, {'nonempty', 'scalar'}, 'Circle', 'Radius');
            
            obj.JavaMessage.setRadius(radius);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Center = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Radius = obj.Radius;
            
            % Recursively copy compound properties
            cpObj.Center = copy(obj.Center);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Radius = strObj.Radius;
            obj.Center = feval([obj.OpencvAppsPoint2DClass '.loadobj'], strObj.Center);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Radius = obj.Radius;
            strObj.Center = saveobj(obj.Center);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.opencv_apps.Circle.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.opencv_apps.Circle;
            obj.reload(strObj);
        end
    end
end
