classdef ContourArray < robotics.ros.Message
    %ContourArray MATLAB implementation of opencv_apps/ContourArray
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'opencv_apps/ContourArray' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'fc54374f45559dfed248b316ccf9181d' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        OpencvAppsContourClass = robotics.ros.msg.internal.MessageFactory.getClassForType('opencv_apps/Contour') % Dispatch to MATLAB class for message type opencv_apps/Contour
    end
    
    properties (Dependent)
        Contours
    end
    
    properties (Access = protected)
        Cache = struct('Contours', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Contours'} % List of non-constant message properties
        ROSPropertyList = {'contours'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ContourArray(msg)
            %ContourArray Construct the message object ContourArray
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function contours = get.Contours(obj)
            %get.Contours Get the value for property Contours
            if isempty(obj.Cache.Contours)
                javaArray = obj.JavaMessage.getContours;
                array = obj.readJavaArray(javaArray, obj.OpencvAppsContourClass);
                obj.Cache.Contours = feval(obj.OpencvAppsContourClass, array);
            end
            contours = obj.Cache.Contours;
        end
        
        function set.Contours(obj, contours)
            %set.Contours Set the value for property Contours
            if ~isvector(contours) && isempty(contours)
                % Allow empty [] input
                contours = feval([obj.OpencvAppsContourClass '.empty'], 0, 1);
            end
            
            validateattributes(contours, {obj.OpencvAppsContourClass}, {'vector'}, 'ContourArray', 'Contours');
            
            javaArray = obj.JavaMessage.getContours;
            array = obj.writeJavaArray(contours, javaArray, obj.OpencvAppsContourClass);
            obj.JavaMessage.setContours(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Contours)
                obj.Cache.Contours = [];
                obj.Cache.Contours = obj.Contours;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Contours = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Contours = copy(obj.Contours);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            ContoursCell = arrayfun(@(x) feval([obj.OpencvAppsContourClass '.loadobj'], x), strObj.Contours, 'UniformOutput', false);
            obj.Contours = vertcat(ContoursCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Contours = arrayfun(@(x) saveobj(x), obj.Contours);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.opencv_apps.ContourArray.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.opencv_apps.ContourArray;
            obj.reload(strObj);
        end
    end
end
