classdef LineArray < robotics.ros.Message
    %LineArray MATLAB implementation of opencv_apps/LineArray
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'opencv_apps/LineArray' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '2b5441933900cc71528395dda29124da' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        OpencvAppsLineClass = robotics.ros.msg.internal.MessageFactory.getClassForType('opencv_apps/Line') % Dispatch to MATLAB class for message type opencv_apps/Line
    end
    
    properties (Dependent)
        Lines
    end
    
    properties (Access = protected)
        Cache = struct('Lines', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Lines'} % List of non-constant message properties
        ROSPropertyList = {'lines'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = LineArray(msg)
            %LineArray Construct the message object LineArray
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function lines = get.Lines(obj)
            %get.Lines Get the value for property Lines
            if isempty(obj.Cache.Lines)
                javaArray = obj.JavaMessage.getLines;
                array = obj.readJavaArray(javaArray, obj.OpencvAppsLineClass);
                obj.Cache.Lines = feval(obj.OpencvAppsLineClass, array);
            end
            lines = obj.Cache.Lines;
        end
        
        function set.Lines(obj, lines)
            %set.Lines Set the value for property Lines
            if ~isvector(lines) && isempty(lines)
                % Allow empty [] input
                lines = feval([obj.OpencvAppsLineClass '.empty'], 0, 1);
            end
            
            validateattributes(lines, {obj.OpencvAppsLineClass}, {'vector'}, 'LineArray', 'Lines');
            
            javaArray = obj.JavaMessage.getLines;
            array = obj.writeJavaArray(lines, javaArray, obj.OpencvAppsLineClass);
            obj.JavaMessage.setLines(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Lines)
                obj.Cache.Lines = [];
                obj.Cache.Lines = obj.Lines;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Lines = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Lines = copy(obj.Lines);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            LinesCell = arrayfun(@(x) feval([obj.OpencvAppsLineClass '.loadobj'], x), strObj.Lines, 'UniformOutput', false);
            obj.Lines = vertcat(LinesCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Lines = arrayfun(@(x) saveobj(x), obj.Lines);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.opencv_apps.LineArray.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.opencv_apps.LineArray;
            obj.reload(strObj);
        end
    end
end
