classdef MomentArray < robotics.ros.Message
    %MomentArray MATLAB implementation of opencv_apps/MomentArray
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'opencv_apps/MomentArray' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'fb51ddd1dea5da45f56842efe759d448' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        OpencvAppsMomentClass = robotics.ros.msg.internal.MessageFactory.getClassForType('opencv_apps/Moment') % Dispatch to MATLAB class for message type opencv_apps/Moment
    end
    
    properties (Dependent)
        Moments
    end
    
    properties (Access = protected)
        Cache = struct('Moments', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Moments'} % List of non-constant message properties
        ROSPropertyList = {'moments'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = MomentArray(msg)
            %MomentArray Construct the message object MomentArray
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function moments = get.Moments(obj)
            %get.Moments Get the value for property Moments
            if isempty(obj.Cache.Moments)
                javaArray = obj.JavaMessage.getMoments;
                array = obj.readJavaArray(javaArray, obj.OpencvAppsMomentClass);
                obj.Cache.Moments = feval(obj.OpencvAppsMomentClass, array);
            end
            moments = obj.Cache.Moments;
        end
        
        function set.Moments(obj, moments)
            %set.Moments Set the value for property Moments
            if ~isvector(moments) && isempty(moments)
                % Allow empty [] input
                moments = feval([obj.OpencvAppsMomentClass '.empty'], 0, 1);
            end
            
            validateattributes(moments, {obj.OpencvAppsMomentClass}, {'vector'}, 'MomentArray', 'Moments');
            
            javaArray = obj.JavaMessage.getMoments;
            array = obj.writeJavaArray(moments, javaArray, obj.OpencvAppsMomentClass);
            obj.JavaMessage.setMoments(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Moments)
                obj.Cache.Moments = [];
                obj.Cache.Moments = obj.Moments;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Moments = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Moments = copy(obj.Moments);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            MomentsCell = arrayfun(@(x) feval([obj.OpencvAppsMomentClass '.loadobj'], x), strObj.Moments, 'UniformOutput', false);
            obj.Moments = vertcat(MomentsCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Moments = arrayfun(@(x) saveobj(x), obj.Moments);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.opencv_apps.MomentArray.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.opencv_apps.MomentArray;
            obj.reload(strObj);
        end
    end
end
