classdef RotatedRect < robotics.ros.Message
    %RotatedRect MATLAB implementation of opencv_apps/RotatedRect
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'opencv_apps/RotatedRect' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '0ae60505c52f020176686d0689b8d390' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        OpencvAppsPoint2DClass = robotics.ros.msg.internal.MessageFactory.getClassForType('opencv_apps/Point2D') % Dispatch to MATLAB class for message type opencv_apps/Point2D
        OpencvAppsSizeClass = robotics.ros.msg.internal.MessageFactory.getClassForType('opencv_apps/Size') % Dispatch to MATLAB class for message type opencv_apps/Size
    end
    
    properties (Dependent)
        Angle
        Center
        Size
    end
    
    properties (Access = protected)
        Cache = struct('Center', [], 'Size', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Angle', 'Center', 'Size'} % List of non-constant message properties
        ROSPropertyList = {'angle', 'center', 'size'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = RotatedRect(msg)
            %RotatedRect Construct the message object RotatedRect
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function angle = get.Angle(obj)
            %get.Angle Get the value for property Angle
            angle = double(obj.JavaMessage.getAngle);
        end
        
        function set.Angle(obj, angle)
            %set.Angle Set the value for property Angle
            validateattributes(angle, {'numeric'}, {'nonempty', 'scalar'}, 'RotatedRect', 'Angle');
            
            obj.JavaMessage.setAngle(angle);
        end
        
        function center = get.Center(obj)
            %get.Center Get the value for property Center
            if isempty(obj.Cache.Center)
                obj.Cache.Center = feval(obj.OpencvAppsPoint2DClass, obj.JavaMessage.getCenter);
            end
            center = obj.Cache.Center;
        end
        
        function set.Center(obj, center)
            %set.Center Set the value for property Center
            validateattributes(center, {obj.OpencvAppsPoint2DClass}, {'nonempty', 'scalar'}, 'RotatedRect', 'Center');
            
            obj.JavaMessage.setCenter(center.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Center)
                obj.Cache.Center.setJavaObject(center.getJavaObject);
            end
        end
        
        function size = get.Size(obj)
            %get.Size Get the value for property Size
            if isempty(obj.Cache.Size)
                obj.Cache.Size = feval(obj.OpencvAppsSizeClass, obj.JavaMessage.getSize);
            end
            size = obj.Cache.Size;
        end
        
        function set.Size(obj, size)
            %set.Size Set the value for property Size
            validateattributes(size, {obj.OpencvAppsSizeClass}, {'nonempty', 'scalar'}, 'RotatedRect', 'Size');
            
            obj.JavaMessage.setSize(size.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Size)
                obj.Cache.Size.setJavaObject(size.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Center = [];
            obj.Cache.Size = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Angle = obj.Angle;
            
            % Recursively copy compound properties
            cpObj.Center = copy(obj.Center);
            cpObj.Size = copy(obj.Size);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Angle = strObj.Angle;
            obj.Center = feval([obj.OpencvAppsPoint2DClass '.loadobj'], strObj.Center);
            obj.Size = feval([obj.OpencvAppsSizeClass '.loadobj'], strObj.Size);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Angle = obj.Angle;
            strObj.Center = saveobj(obj.Center);
            strObj.Size = saveobj(obj.Size);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.opencv_apps.RotatedRect.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.opencv_apps.RotatedRect;
            obj.reload(strObj);
        end
    end
end
