classdef Matrix < robotics.ros.Message
    %Matrix MATLAB implementation of apriltags2_ros/Matrix
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'apriltags2_ros/Matrix' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '0d22ff0f5c1d363f0ac7a539f9a6b18f' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Nrows
        Ncols
        Data
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Data', 'Ncols', 'Nrows'} % List of non-constant message properties
        ROSPropertyList = {'data', 'ncols', 'nrows'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Matrix(msg)
            %Matrix Construct the message object Matrix
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function nrows = get.Nrows(obj)
            %get.Nrows Get the value for property Nrows
            nrows = int8(obj.JavaMessage.getNrows);
        end
        
        function set.Nrows(obj, nrows)
            %set.Nrows Set the value for property Nrows
            validateattributes(nrows, {'numeric'}, {'nonempty', 'scalar'}, 'Matrix', 'Nrows');
            
            obj.JavaMessage.setNrows(nrows);
        end
        
        function ncols = get.Ncols(obj)
            %get.Ncols Get the value for property Ncols
            ncols = int8(obj.JavaMessage.getNcols);
        end
        
        function set.Ncols(obj, ncols)
            %set.Ncols Set the value for property Ncols
            validateattributes(ncols, {'numeric'}, {'nonempty', 'scalar'}, 'Matrix', 'Ncols');
            
            obj.JavaMessage.setNcols(ncols);
        end
        
        function data = get.Data(obj)
            %get.Data Get the value for property Data
            javaArray = obj.JavaMessage.getData;
            array = obj.readJavaArray(javaArray, 'double');
            data = double(array);
        end
        
        function set.Data(obj, data)
            %set.Data Set the value for property Data
            if ~isvector(data) && isempty(data)
                % Allow empty [] input
                data = double.empty(0,1);
            end
            
            validateattributes(data, {'numeric'}, {'vector'}, 'Matrix', 'Data');
            
            javaArray = obj.JavaMessage.getData;
            array = obj.writeJavaArray(data, javaArray, 'double');
            obj.JavaMessage.setData(array);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Nrows = obj.Nrows;
            cpObj.Ncols = obj.Ncols;
            cpObj.Data = obj.Data;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Nrows = strObj.Nrows;
            obj.Ncols = strObj.Ncols;
            obj.Data = strObj.Data;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Nrows = obj.Nrows;
            strObj.Ncols = obj.Ncols;
            strObj.Data = obj.Data;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.apriltags2_ros.Matrix.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.apriltags2_ros.Matrix;
            obj.reload(strObj);
        end
    end
end
